/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <glib.h>
#include <unistd.h>
#include <libnotify/notify.h>
/* Header for class edu_rf_notification_NotifierBridge */

#ifndef _Included_edu_rf_notification_NotifierBridge
#define _Included_edu_rf_notification_NotifierBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_rf_notification_NotifierBridge
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_rf_notification_NotifierBridge_destroy (JNIEnv *, jobject);
/*
 * Class:     edu_rf_notification_NotifierBridge
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_rf_notification_NotifierBridge_init (JNIEnv *, jobject);

/*
 * Class:     edu_rf_notification_NotifierBridge
 * Method:    displayMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_rf_notification_NotifierBridge_displayMessage (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
